Add .svg version of black/white shield
datasektionen/UI pull request #1
Opened 2017-10-15 00:32 UTC by Plongy

By popular demand

Tänker mig att @macfeaster dock vill att jag ska skapa en PR till hans heliga repo...

2017-10-15 00:34 UTC, Plongy commented
Inte helt 100 på skuggorna, skapade en liten skugga viktad lägre i figuren...

2017-10-17 10:48 UTC, macfeaster requested changes
När jag kollar ser det ut som att bara de gula "solstrålarna" har skugga och inte cerisa cirkeln? Båda ska ha skuggning.

Det vita deltat saknar helt skugga, se PDF för hur det ska se ut.

2017-10-17 22:17 UTC, Plongy commented
Oh, kollar på det sen vid tillfälle

2017-11-01 09:15 UTC, macfeaster commented
Alltså, skuggan på vita deltat är fortfarande jättekonstig. Går det inte att bara konvertera PDFen till SVG?

2017-11-01 09:18 UTC, macfeaster requested changes
Fortfarande märklig skuggning

2025-06-12 08:01 UTC, closed without merging